[tool.poetry]
name = "chat"
version = "0.0.0"
description = "Chat is a python library that allows provides tools for legal insights chat."
authors = ["Yassin Kortam"]
license = "MIT"
readme = "README.md"